# -*- coding: utf-8 -*-
"""Normalization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J_GPp7IqcXG6jzpb6kZENIPIPGeDvEXF
"""

# modules we'll use
import pandas as pd
import numpy as np

# for Box-Cox Transformation
from scipy import stats

# for min_max scaling
from mlxtend.preprocessing import minmax_scaling

# plotting modules
import seaborn as sns
import matplotlib.pyplot as plt

# set seed for reproducibility
np.random.seed(0)

from google.colab import files
up=files.upload()

df = pd.read_csv("WHA.csv")
df.head(10)

ds = pd.DataFrame(df)

print(ds)

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

normalized_data = scaler.fit_transform(ds)

print(normalized_data)

normalized_ds = pd.DataFrame(normalized_data, columns=ds.columns)

print(normalized_ds)

fig, ax = plt.subplots(1, 2, figsize=(15, 3))
sns.histplot(ds, ax=ax[0], kde=True, legend=False)
ax[0].set_title("Original Data")
sns.histplot(ds, ax=ax[1], kde=True, legend=False)
ax[1].set_title("Scaled data")
plt.show()

fig, ax=plt.subplots(1, 2, figsize=(15, 3))
sns.histplot(ds, ax=ax[0], kde=True, legend=False)
ax[0].set_title("Original Data")
sns.histplot(normalized_data[0], ax=ax[1], kde=True, legend=False)
ax[1].set_title("Normalized data")
plt.show()

